version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-password}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-move4good}
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  python:
    image: python:3.11
    container_name: python_container
    command: ["bash", "-c", "pip install -r requirement.txt && python app/main.py"]
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-move4good}
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    working_dir: /app

volumes:
  mysql_data:
