version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: locator
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  python:
    image: python:3.11
    container_name: python_container
    command: ["bash", "-c", "pip install -r requirement.txt && python backend/main.py"]
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    working_dir: /app

volumes:
  mysql_data:
